version: "3.8"

services:
  kong-dp:
    image: kong/kong-gateway:3.12
    container_name: kong-dp
    restart: unless-stopped
    environment:
      KONG_ROLE: data_plane
      KONG_DATABASE: off
      KONG_VITALS: off
      KONG_CLUSTER_MTLS: pki
      KONG_CLUSTER_CONTROL_PLANE: 3be3aa06b5.us.cp.konghq.com:443
      KONG_CLUSTER_SERVER_NAME: 3be3aa06b5.us.cp.konghq.com
      KONG_CLUSTER_TELEMETRY_ENDPOINT: 3be3aa06b5.us.tp.konghq.com:443
      KONG_CLUSTER_TELEMETRY_SERVER_NAME: 3be3aa06b5.us.tp.konghq.com

      KONG_CLUSTER_CERT: |
        -----BEGIN CERTIFICATE-----
        MIICDjCCAbSgAwIBAgIBATAKBggqhkjOPQQDBDA4MTYwCQYDVQQGEwJVUzApBgNV
        BAMeIgBrAG8AbgBuAGUAYwB0AC0ASwBPAE4ARwAgADIAMAAyADYwHhcNMjUxMDA2
        MDI1NzEwWhcNMzUxMDA2MDI1NzEwWjA4MTYwCQYDVQQGEwJVUzApBgNVBAMeIgBr
        AG8AbgBuAGUAYwB0AC0ASwBPAE4ARwAgADIAMAAyADYwWTATBgcqhkjOPQIBBggq
        hkjOPQMBBwNCAATA2GiVAG+tldbmduaX7txiFs+RSxlEZvBJ6SGo2rQ2qSRLHJCd
        6j0cj1hVuzCII02GmrUbSOqWKSUd4vL0nsVpo4GuMIGrMAwGA1UdEwEB/wQCMAAw
        CwYDVR0PBAQDAgAGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAXBgkr
        BgEEAYI3FAIECgwIY2VydFR5cGUwIwYJKwYBBAGCNxUCBBYEFAEBAQEBAQEBAQEB
        AQEBAQEBAQEBMBwGCSsGAQQBgjcVBwQPMA0GBSkBAQEBAgEKAgEUMBMGCSsGAQQB
        gjcVAQQGAgQAFAAKMAoGCCqGSM49BAMEA0gAMEUCIQCx4m9vR2FzsXDlBHzlmiev
        cFLY33Qy2J0KJM4pDfMHIwIgHeij378TVVkZ9/3eld1lleYOfj6q2/7wNOGXr12B
        cyU=
        -----END CERTIFICATE-----

      KONG_CLUSTER_CERT_KEY: |
        -----BEGIN PRIVATE KEY-----
        MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgU4K7JAiTjQDsat9r
        4klW3uknmfA4HDwFnsYh5CJ8SkCgCgYIKoZIzj0DAQehRANCAATA2GiVAG+tldbm
        duaX7txiFs+RSxlEZvBJ6SGo2rQ2qSRLHJCd6j0cj1hVuzCII02GmrUbSOqWKSUd
        4vL0nsVp
        -----END PRIVATE KEY-----

      KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
      KONG_KONNECT_MODE: on
      KONG_CLUSTER_DP_LABELS: type:docker,os:windows
      KONG_ROUTER_FLAVOR: expressions
      KONG_STATUS_LISTEN: 0.0.0.0:8100
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8100:8100"
    networks:
      - kong-net

  mockapi:
    image: kennethreitz/httpbin
    container_name: mockapi
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - kong-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - kong-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - kong-net

  prometheus-connector:
    build: ./prometheus-connector
    container_name: prometheus-connector
    restart: unless-stopped
    ports:
      - "8005:8005"
    networks:
      - kong-net
    depends_on:
      - prometheus

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    tty: true
    volumes:
      - ollama:/root/.ollama
    networks:
      - kong-net

  openwebui:
    image: ghcr.io/open-webui/open-webui:0.6.32
    container_name: openwebui
    restart: unless-stopped
    depends_on:
      - ollama
    ports:
      - "8082:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=please-change-me-123
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - openwebui-data:/app/backend/data
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge

volumes:
  ollama: {}
  openwebui-data: {}
